// Client-safe: questions, options, difficulty, and category only.
// Correct answers live in lib/answerKey.js (server-only).
//
// 200 questions: 60 easy (30%) + 140 tough (70%)
// Categories (5): nutrition, lifestyle, mindset, medical, programs
const questions = [
  // ---------------- NUTRITION (easy) ----------------
  { id: "nut1", category: "nutrition", difficulty: "easy", q: "How many things does RF recommend avoiding on a daily basis?", options: ["5", "3", "7"] },
  { id: "nut2", category: "nutrition", difficulty: "easy", q: "Which of these is the exception RF says is fine occasionally (not on the daily-avoid list)?", options: ["Deep fried food", "Packet food", "Fresh fruit"] },
  { id: "nut3", category: "nutrition", difficulty: "easy", q: "Into how many parts does RF divide all food?", options: ["2", "5", "3"] },
  { id: "nut4", category: "nutrition", difficulty: "easy", q: "Which of RF's three food categories should be eaten the least?", options: ["Plant food", "Fruits", "Animal food"] },
  { id: "nut5", category: "nutrition", difficulty: "easy", q: "Where is fiber found, according to RF?", options: ["In animal food", "Only in plant food", "In packet food"] },
  { id: "nut6", category: "nutrition", difficulty: "easy", q: "What is RF's core philosophy instead of eating less?", options: ["Eating right", "Eating less", "Skipping meals"] },
  { id: "nut7", category: "nutrition", difficulty: "easy", q: "How many times a day does RF recommend eating cooked food (except for weight-gain cases)?", options: ["3 times", "2 times", "4 times"] },
  { id: "nut8", category: "nutrition", difficulty: "easy", q: "What does RF say we should focus on, rather than counting calories?", options: ["Nutrients", "Portion size", "Calorie counting"] },
  { id: "nut9", category: "nutrition", difficulty: "easy", q: "What does RF say is the world's #1 source of calcium (not milk)?", options: ["Almonds", "White sesame seeds", "Spinach"] },
  { id: "nut10", category: "nutrition", difficulty: "easy", q: "Which food group does RF recommend building most of your plate around?", options: ["Plant food", "Animal food", "Processed food"] },
  { id: "nut11", category: "nutrition", difficulty: "easy", q: "According to RF, which of these is a healthy whole-food sweetener used in moderation?", options: ["Dates", "Refined sugar", "Corn syrup"] },
  { id: "nut12", category: "nutrition", difficulty: "easy", q: "Which type of grain does RF generally recommend over refined white rice?", options: ["White bread", "Millets and whole grains", "Maida"] },

  // ---------------- NUTRITION (tough) ----------------
  { id: "nut13", category: "nutrition", difficulty: "tough", q: "According to RF, when do mammals naturally produce milk?", options: ["Only when pregnant or lactating", "All the time", "Only during childhood"] },
  { id: "nut14", category: "nutrition", difficulty: "tough", q: "What health issues does RF link to hormonal imbalance from regular milk product consumption?", options: ["Only weight gain", "Only thyroid issues", "Overweight, thyroid problems, and PCOD"] },
  { id: "nut15", category: "nutrition", difficulty: "tough", q: "What is the food source for the trillions of gut bacteria, per RF?", options: ["Protein", "Sugar", "Fiber"] },
  { id: "nut16", category: "nutrition", difficulty: "tough", q: "What is a 'phytonutrient', according to RF?", options: ["A synthetic vitamin supplement", "A type of protein supplement", "Plant-based compounds/colors that provide antioxidant benefits"] },
  { id: "nut17", category: "nutrition", difficulty: "tough", q: "Why does RF say caffeine shouldn't be had daily?", options: ["It has too many calories", "It's a stimulant and not gut-friendly", "It causes weight gain directly"] },
  { id: "nut18", category: "nutrition", difficulty: "tough", q: "According to RF, what should be done if someone is deficient in D3 or B12 on a plant-based diet?", options: ["Nothing, plant food covers it entirely", "Take a supplement for the deficient one", "Add more milk products"] },
  { id: "nut19", category: "nutrition", difficulty: "tough", q: "How many rules does RF give for drinking water?", options: ["5 rules", "3 rules", "7 rules"] },
  { id: "nut20", category: "nutrition", difficulty: "tough", q: "What does RF say about milk as a calcium source compared to sesame seeds?", options: ["Milk is superior", "Sesame seeds are a richer source", "They are equal"] },
  { id: "nut21", category: "nutrition", difficulty: "tough", q: "Which of these does RF say feeds bad gut bacteria?", options: ["Fiber", "Sugar and processed food", "Fresh vegetables"] },
  { id: "nut22", category: "nutrition", difficulty: "tough", q: "What does RF suggest as a daily drink to support digestion?", options: ["Warm water", "Cold soft drinks", "Sweetened tea"] },
  { id: "nut23", category: "nutrition", difficulty: "tough", q: "According to RF, what is a common mistake people make with fruit juice?", options: ["They drink the whole fruit including fiber", "They discard the fiber and drink only the juice", "They add sugar"] },
  { id: "nut24", category: "nutrition", difficulty: "tough", q: "Which oil does RF generally caution against for daily cooking?", options: ["Cold-pressed oils", "Refined seed oils", "Ghee in moderation"] },
  { id: "nut25", category: "nutrition", difficulty: "tough", q: "What is the recommended gap between dinner and sleep, per RF?", options: ["At least 2-3 hours", "30 minutes", "No gap needed"] },
  { id: "nut26", category: "nutrition", difficulty: "tough", q: "What does RF say is the effect of deep fried food on the body?", options: ["Supports gut health", "Increases inflammation and disease risk", "Boosts immunity"] },
  { id: "nut27", category: "nutrition", difficulty: "tough", q: "Which nutrient is essential for absorbing Vitamin D3?", options: ["Calcium", "Fat", "Iron"] },
  { id: "nut28", category: "nutrition", difficulty: "tough", q: "According to RF, what is the problem with eating late at night?", options: ["Digestion is impaired and it disrupts sleep", "It boosts metabolism", "It has no effect"] },
  { id: "nut29", category: "nutrition", difficulty: "tough", q: "What is a key difference between plant and animal protein per RF?", options: ["Animal protein is lower in fiber and linked to inflammation", "Plant protein contains cholesterol", "There is no difference"] },
  { id: "nut30", category: "nutrition", difficulty: "tough", q: "What does RF say about refined salt?", options: ["It is the same as rock salt", "Rock salt/mineral salt is preferred", "It contains more minerals"] },
  { id: "nut31", category: "nutrition", difficulty: "tough", q: "How does RF recommend eating fruits relative to heavy meals?", options: ["With meals always", "Separate from heavy meals", "Never"] },
  { id: "nut32", category: "nutrition", difficulty: "tough", q: "What is the role of water in RF's gut health guidance?", options: ["Flushes toxins and supports digestion", "Only quenches thirst", "Replaces meals"] },
  { id: "nut33", category: "nutrition", difficulty: "tough", q: "What does RF say about processed packet food?", options: ["It is fine in moderation", "It contains preservatives and additives that harm the gut", "It is nutritionally superior"] },
  { id: "nut34", category: "nutrition", difficulty: "tough", q: "According to RF, which meal is most important to keep light?", options: ["Breakfast", "Dinner", "Lunch"] },
  { id: "nut35", category: "nutrition", difficulty: "tough", q: "What does RF say about artificial sweeteners like aspartame?", options: ["They are healthier than sugar", "They are artificial and can disturb gut health", "They are natural"] },
  { id: "nut36", category: "nutrition", difficulty: "tough", q: "Which of these does RF associate with regular milk consumption in adults?", options: ["Lactose buildup and mucus", "Better calcium absorption always", "Healthier bones"] },
  { id: "nut37", category: "nutrition", difficulty: "tough", q: "What is the ideal way to consume seeds per RF?", options: ["Soaked seeds", "Deep fried seeds", "Coated in sugar"] },
  { id: "nut38", category: "nutrition", difficulty: "tough", q: "What does RF say about eating when stressed?", options: ["It is the best time to eat", "Digestion suffers when stressed", "It improves absorption"] },
  { id: "nut39", category: "nutrition", difficulty: "tough", q: "How much water does RF roughly suggest daily?", options: ["About 1 liter", "About 2-3 liters adjusted to needs", "More than 6 liters always"] },
  { id: "nut40", category: "nutrition", difficulty: "tough", q: "What is RF's view on ghee?", options: ["Avoid completely", "Use in moderation, traditionally prepared", "Unlimited amounts"] },

  // ---------------- LIFESTYLE (easy) ----------------
  { id: "lif1", category: "lifestyle", difficulty: "easy", q: "How many hours of intermittent fasting does RF recommend for everyone?", options: ["8 hours", "12 hours", "16 hours"] },
  { id: "lif2", category: "lifestyle", difficulty: "easy", q: "How many pillars of good health does RF identify?", options: ["3", "5", "7"] },
  { id: "lif3", category: "lifestyle", difficulty: "easy", q: "What is the first thing RF recommends after waking up?", options: ["Drink warm water", "Drink cold coffee", "Eat immediately"] },
  { id: "lif4", category: "lifestyle", difficulty: "easy", q: "What time does RF suggest for the last meal of the day?", options: ["Late night", "Before sunset or early evening", "Midnight"] },
  { id: "lif5", category: "lifestyle", difficulty: "easy", q: "Which of these does RF consider a pillar of health?", options: ["Sleep", "Smoking", "Junk food"] },
  { id: "lif6", category: "lifestyle", difficulty: "easy", q: "How much sleep does RF generally recommend each night?", options: ["4-5 hours", "7-8 hours", "10-12 hours"] },
  { id: "lif7", category: "lifestyle", difficulty: "easy", q: "What does RF say about eating within a fixed window?", options: ["It supports digestion and metabolism", "It has no benefit", "It is harmful"] },
  { id: "lif8", category: "lifestyle", difficulty: "easy", q: "What should you do right after waking up per RF?", options: ["Reach for the phone", "Get sunlight and warm water", "Skip breakfast always"] },
  { id: "lif9", category: "lifestyle", difficulty: "easy", q: "Does RF recommend daily movement and exercise?", options: ["Yes, movement is a pillar of health", "No", "Only once a month"] },
  { id: "lif10", category: "lifestyle", difficulty: "easy", q: "What is the best time to get sunlight per RF?", options: ["Early morning", "Midnight", "Afternoon in peak heat"] },
  { id: "lif11", category: "lifestyle", difficulty: "easy", q: "Which habit does RF say disrupts sleep?", options: ["Fixed sleep timing", "Late-night screen use", "Cool dark room"] },
  { id: "lif12", category: "lifestyle", difficulty: "easy", q: "What does RF say about skipping breakfast?", options: ["Always harmful", "Fasting windows make it acceptable in context", "Eat double later"] },

  // ---------------- LIFESTYLE (tough) ----------------
  { id: "lif13", category: "lifestyle", difficulty: "tough", q: "When does most of the immune system's cancer-cell killing happen, according to RF?", options: ["During the day", "In the first half of the night", "In the second half of the night"] },
  { id: "lif14", category: "lifestyle", difficulty: "tough", q: "What happens to ghrelin levels when we don't get enough sleep?", options: ["It increases, causing more hunger", "It decreases", "It stays exactly the same"] },
  { id: "lif15", category: "lifestyle", difficulty: "tough", q: "How many hours before bed should you avoid heavy food per RF?", options: ["1 hour", "2-3 hours", "15 minutes"] },
  { id: "lif16", category: "lifestyle", difficulty: "tough", q: "What does RF say about the timing of dinner relative to the sleep window?", options: ["Dinner right before bed", "Dinner should be early, leaving a gap", "No timing rule"] },
  { id: "lif17", category: "lifestyle", difficulty: "tough", q: "Which hormone is disrupted by late-night light exposure per RF?", options: ["Insulin always", "Melatonin", "Testosterone"] },
  { id: "lif18", category: "lifestyle", difficulty: "tough", q: "What does RF recommend for weight-gain cases regarding meal frequency?", options: ["Skip meals", "More frequent small meals", "Only liquid diet"] },
  { id: "lif19", category: "lifestyle", difficulty: "tough", q: "According to RF, what happens to digestion at night?", options: ["No change", "Digestive fire is lower at night", "It is highest at night"] },
  { id: "lif20", category: "lifestyle", difficulty: "tough", q: "What is RF's view on chronic dieting?", options: ["Extreme restriction is best", "Sustainable habit change is better", "Crash diets are recommended"] },
  { id: "lif21", category: "lifestyle", difficulty: "tough", q: "What does RF say about morning sunlight and circadian rhythm?", options: ["It has no effect", "It resets the body clock", "It only affects skin"] },
  { id: "lif22", category: "lifestyle", difficulty: "tough", q: "How long after a meal does RF suggest light walking?", options: ["Immediately intense exercise", "10-15 minutes", "2 hours of complete rest"] },
  { id: "lif23", category: "lifestyle", difficulty: "tough", q: "What does RF say about napping habits?", options: ["Long naps daily are ideal", "Short naps are okay, long day sleeps disrupt night sleep", "Never nap"] },
  { id: "lif24", category: "lifestyle", difficulty: "tough", q: "What is the effect of chronic sleep deprivation per RF?", options: ["No effect", "Hormonal imbalance and increased disease risk", "Improves metabolism"] },
  { id: "lif25", category: "lifestyle", difficulty: "tough", q: "What does RF say about excessive air-conditioning?", options: ["It is always healthy", "Overuse can dry and stress the body", "It improves immunity"] },
  { id: "lif26", category: "lifestyle", difficulty: "tough", q: "What does RF suggest about electronic devices before bed?", options: ["Use them until sleep", "Avoid screens an hour before sleep", "Screens help you sleep"] },
  { id: "lif27", category: "lifestyle", difficulty: "tough", q: "What time does RF consider ideal to wake up?", options: ["Midday", "Early morning (before/around sunrise)", "Late afternoon"] },
  { id: "lif28", category: "lifestyle", difficulty: "tough", q: "What does RF say about regularity of meal times?", options: ["Irregularity is fine", "Eating at consistent times supports the body", "Only weekends matter"] },
  { id: "lif29", category: "lifestyle", difficulty: "tough", q: "What is RF's stance on extreme exercise?", options: ["More extreme is always better", "Balanced movement is better than extreme strain", "No exercise at all"] },
  { id: "lif30", category: "lifestyle", difficulty: "tough", q: "What does RF say about weekend lifestyle swings?", options: ["They are harmless", "They disrupt the body's rhythm", "They boost health"] },
  { id: "lif31", category: "lifestyle", difficulty: "tough", q: "How does RF suggest dealing with late-night hunger?", options: ["Heavy fried food", "A small healthy snack or an earlier dinner", "Skip all water"] },
  { id: "lif32", category: "lifestyle", difficulty: "tough", q: "What is the recommended gap between the last meal and morning breakfast?", options: ["No gap", "Intermittent fasting window of 12-16 hours", "2 hours"] },
  { id: "lif33", category: "lifestyle", difficulty: "tough", q: "What does RF say about eating while watching screens?", options: ["It improves appetite", "Mindless eating harms digestion", "No effect"] },
  { id: "lif34", category: "lifestyle", difficulty: "tough", q: "Which practice does RF link to better deep sleep?", options: ["Irregular naps", "Consistent sleep-wake timing", "Late caffeine"] },
  { id: "lif35", category: "lifestyle", difficulty: "tough", q: "What does RF recommend for joint and body flexibility?", options: ["Complete rest", "Regular movement and stretching", "Strenuous running daily"] },
  { id: "lif36", category: "lifestyle", difficulty: "tough", q: "How does RF view late-night work and health?", options: ["It is the most productive and healthy", "It can disrupt hormonal balance", "No effect"] },
  { id: "lif37", category: "lifestyle", difficulty: "tough", q: "What should your dinner portion be relative to lunch per RF?", options: ["Heavier than lunch", "Lighter than lunch", "Same as lunch"] },
  { id: "lif38", category: "lifestyle", difficulty: "tough", q: "What does RF say about drinking large amounts of water with meals?", options: ["Drink a full liter with every meal", "Sip small amounts, avoid large gulps with food", "Only ice-cold water"] },
  { id: "lif39", category: "lifestyle", difficulty: "tough", q: "What is RF's view on a regular daily routine?", options: ["Random schedules are better", "A steady routine supports health", "Routine is stressful"] },
  { id: "lif40", category: "lifestyle", difficulty: "tough", q: "What does RF say about meal timing while traveling?", options: ["Abandon all rules while traveling", "Try to maintain meal timing even while traveling", "Skip eating on travel days"] },

  // ---------------- MINDSET (easy) ----------------
  { id: "min1", category: "mindset", difficulty: "easy", q: "How many main concepts does RF follow?", options: ["5", "6", "8"] },
  { id: "min2", category: "mindset", difficulty: "easy", q: "What are the two things RF says go into our body/mind every day?", options: ["Sleep and exercise", "Food and our thoughts/emotions", "Medicine and rest"] },
  { id: "min3", category: "mindset", difficulty: "easy", q: "Which energy centers does RF's breathwork aim to release lower emotions from?", options: ["The upper 3 energy centers", "The lower 3 energy centers", "All 8 energy centers equally"] },
  { id: "min4", category: "mindset", difficulty: "easy", q: "How many main things does RF's unique meditation program teach?", options: ["3 things", "5 things", "4 things"] },
  { id: "min5", category: "mindset", difficulty: "easy", q: "What does RF say about negative thoughts?", options: ["They can be released through practices", "They must be suppressed forever", "They have no impact"] },
  { id: "min6", category: "mindset", difficulty: "easy", q: "What is the role of meditation per RF?", options: ["Calming the mind and releasing stored emotions", "Only relaxation for sleep", "A replacement for exercise"] },
  { id: "min7", category: "mindset", difficulty: "easy", q: "What does RF say about practicing gratitude?", options: ["It improves mental health", "It is a myth", "Only for children"] },
  { id: "min8", category: "mindset", difficulty: "easy", q: "What is 'mindfulness' in RF's context?", options: ["Being present and aware", "Forgetting everything", "Worrying about the past"] },
  { id: "min9", category: "mindset", difficulty: "easy", q: "What does RF say about stress?", options: ["It is normal but must be managed", "It is always good", "It has no effect"] },
  { id: "min10", category: "mindset", difficulty: "easy", q: "Which practice does RF use to release stored emotions?", options: ["Breathwork and meditation", "Suppressing feelings", "Ignoring them"] },
  { id: "min11", category: "mindset", difficulty: "easy", q: "What does RF say about self-love?", options: ["It is the foundation of health", "It is selfish", "Only for special occasions"] },
  { id: "min12", category: "mindset", difficulty: "easy", q: "What does RF say about positive affirmations?", options: ["They support a healthy mindset", "They are useless", "They replace food"] },

  // ---------------- MINDSET (tough) ----------------
  { id: "min13", category: "mindset", difficulty: "tough", q: "Roughly how many thoughts does a person have per day, according to RF?", options: ["10,000-20,000", "60,000-70,000", "100,000+"] },
  { id: "min14", category: "mindset", difficulty: "tough", q: "How many energy centers does RF describe in the body?", options: ["3", "5", "7"] },
  { id: "min15", category: "mindset", difficulty: "tough", q: "What does RF say is stored in the lower energy centers?", options: ["Lower emotions like fear and guilt", "Only physical strength", "No emotions"] },
  { id: "min16", category: "mindset", difficulty: "tough", q: "Which type of breathing does RF use to release lower emotions?", options: ["Shallow chest breathing", "Deep breathing through the lower centers", "Holding breath until dizzy"] },
  { id: "min17", category: "mindset", difficulty: "tough", q: "What does RF say about the connection between emotions and disease?", options: ["Unreleased emotions can contribute to disease", "Emotions never affect health", "Only food matters"] },
  { id: "min18", category: "mindset", difficulty: "tough", q: "What does RF say about forgiveness?", options: ["It helps release emotional baggage", "It is a sign of weakness", "Only for others' benefit"] },
  { id: "min19", category: "mindset", difficulty: "tough", q: "How does RF recommend dealing with anxious thoughts?", options: ["Breathwork and present-moment awareness", "Dwelling on them", "Ignoring sleep"] },
  { id: "min20", category: "mindset", difficulty: "tough", q: "What is 'meditation with intent' per RF?", options: ["Random daydreaming", "A focused practice to transform the self", "Only a breathing exercise"] },
  { id: "min21", category: "mindset", difficulty: "tough", q: "What does RF say about the mind-body connection?", options: ["The mind strongly influences the body", "The body ignores the mind", "Only genetics matter"] },
  { id: "min22", category: "mindset", difficulty: "tough", q: "What is the effect of chronic worry per RF?", options: ["Increases stress hormones and harms health", "Builds immunity", "Improves sleep"] },
  { id: "min23", category: "mindset", difficulty: "tough", q: "What does RF say about childhood emotional patterns?", options: ["They can influence adult health and need release", "They are irrelevant", "Only diet matters"] },
  { id: "min24", category: "mindset", difficulty: "tough", q: "What is the purpose of RF's breathing exercises?", options: ["To release stored lower emotions", "To hold breath longer for sport", "To strengthen vocal cords"] },
  { id: "min25", category: "mindset", difficulty: "tough", q: "What does RF say about positive thinking vs denial?", options: ["Positive thinking is active, not denial", "They are the same", "Denial is healthier"] },
  { id: "min26", category: "mindset", difficulty: "tough", q: "What happens when emotions are repeatedly suppressed per RF?", options: ["They can accumulate and manifest as health issues", "They disappear completely", "They turn into muscle"] },
  { id: "min27", category: "mindset", difficulty: "tough", q: "What does RF say about releasing childhood trauma?", options: ["Releasing childhood trauma can heal the present", "It is a myth", "Only for psychologists"] },
  { id: "min28", category: "mindset", difficulty: "tough", q: "What is the role of intention in RF meditation?", options: ["It directs the transformation", "It is unnecessary", "It only applies to food"] },
  { id: "min29", category: "mindset", difficulty: "tough", q: "What does RF say about a daily gratitude practice?", options: ["It rewires the mind toward positivity", "It is superstition", "It only works in groups"] },
  { id: "min30", category: "mindset", difficulty: "tough", q: "What is the link between gut health and mood per RF?", options: ["The gut produces most serotonin, affecting mood", "No link", "Only the brain matters"] },
  { id: "min31", category: "mindset", difficulty: "tough", q: "What does RF say about letting go of the past?", options: ["It frees the mind for healing", "It is impossible", "It has no effect"] },
  { id: "min32", category: "mindset", difficulty: "tough", q: "How does RF view emotional eating?", options: ["It's a sign of unaddressed emotions", "It's the best diet", "Only happens to children"] },
  { id: "min33", category: "mindset", difficulty: "tough", q: "What does RF say about self-talk?", options: ["Kind self-talk supports mental health", "Harsh self-talk is motivating", "Words have no effect"] },
  { id: "min34", category: "mindset", difficulty: "tough", q: "What is a core teaching of RF's meditation on love?", options: ["Self-love and compassion transform health", "Love is only for others", "Meditation is a chore"] },
  { id: "min35", category: "mindset", difficulty: "tough", q: "What does RF say about the power of breath?", options: ["It calms the nervous system instantly", "It only fills the lungs", "It is useless for stress"] },
  { id: "min36", category: "mindset", difficulty: "tough", q: "What does RF say about carrying grudges?", options: ["They drain energy and harm health", "They are healthy", "They improve immunity"] },
  { id: "min37", category: "mindset", difficulty: "tough", q: "What is the 'release' step in RF breathing?", options: ["Exhaling fully and letting go", "Inhaling deeply only", "Holding breath"] },
  { id: "min38", category: "mindset", difficulty: "tough", q: "What does RF say about fear and the body?", options: ["Chronic fear triggers stress responses", "Fear is only mental", "Fear strengthens immunity"] },
  { id: "min39", category: "mindset", difficulty: "tough", q: "What does RF recommend for a racing mind before sleep?", options: ["Breathing exercises to calm it", "More caffeine", "Loud music"] },
  { id: "min40", category: "mindset", difficulty: "tough", q: "What does RF say about living with purpose?", options: ["Living with purpose improves health", "Only work matters", "Purpose is a myth"] },

  // ---------------- MEDICAL (easy) ----------------
  { id: "med1", category: "medical", difficulty: "easy", q: "What percentage of our immunity lies in the gut, according to RF?", options: ["50%", "70%", "85%"] },
  { id: "med2", category: "medical", difficulty: "easy", q: "What is often called the 'powerhouse of the cell'?", options: ["Mitochondria", "Nucleus", "Ribosome"] },
  { id: "med3", category: "medical", difficulty: "easy", q: "What does HDL stand for?", options: ["Heavy Density Lipid", "High-Density Lipoprotein", "Hormonal Density Level"] },
  { id: "med4", category: "medical", difficulty: "easy", q: "Which test measures average blood sugar over the past 3 months?", options: ["Fasting blood sugar", "HbA1c", "Lipid profile"] },
  { id: "med5", category: "medical", difficulty: "easy", q: "What organ does RF say is central to detoxification?", options: ["Liver", "Ears", "Skin color"] },
  { id: "med6", category: "medical", difficulty: "easy", q: "What is the main fuel of the brain?", options: ["Glucose", "Protein", "Fat"] },
  { id: "med7", category: "medical", difficulty: "easy", q: "What does RF say about most chronic diseases?", options: ["They are largely lifestyle-driven", "Only genetic", "Only infectious"] },
  { id: "med8", category: "medical", difficulty: "easy", q: "What does insulin do?", options: ["Lowers blood sugar", "Raises blood sugar", "Builds bone"] },
  { id: "med9", category: "medical", difficulty: "easy", q: "What does blood pressure measure?", options: ["Force of blood on artery walls", "Blood sugar level", "Cholesterol count"] },
  { id: "med10", category: "medical", difficulty: "easy", q: "What is Vitamin D mainly important for?", options: ["Bone and immune health", "Only skin color", "Only hair growth"] },
  { id: "med11", category: "medical", difficulty: "easy", q: "What is a main dietary contributor to fatty liver per RF?", options: ["Excess sugar and refined food", "Too much fiber", "Water"] },
  { id: "med12", category: "medical", difficulty: "easy", q: "What do thyroid hormones control?", options: ["Metabolism", "Only weight", "Only mood"] },

  // ---------------- MEDICAL (tough) ----------------
  { id: "med13", category: "medical", difficulty: "tough", q: "What percentage of serotonin (the mood hormone) is produced in the gut, per RF?", options: ["50%", "Around 90%", "10%"] },
  { id: "med14", category: "medical", difficulty: "tough", q: "What hormone does RF call the 'hunger hormone'?", options: ["Leptin", "Ghrelin", "Insulin"] },
  { id: "med15", category: "medical", difficulty: "tough", q: "What hormone tells your brain you're full, per RF's list?", options: ["Ghrelin", "Leptin", "Cortisol"] },
  { id: "med16", category: "medical", difficulty: "tough", q: "What does the C-peptide blood test measure?", options: ["Blood sugar directly", "How much insulin the pancreas is producing", "Cholesterol levels"] },
  { id: "med17", category: "medical", difficulty: "tough", q: "What does the vagus nerve connect the brain to?", options: ["Only the lungs", "Organs like the heart, lungs, and gut", "The skin"] },
  { id: "med18", category: "medical", difficulty: "tough", q: "What is considered the normal range for fasting insulin?", options: ["Less than 5 µIU/mL", "Less than 25 µIU/mL", "Less than 100 µIU/mL"] },
  { id: "med19", category: "medical", difficulty: "tough", q: "What does high fasting insulin usually indicate?", options: ["Excellent metabolic health", "Pre-diabetes and insulin resistance", "Nothing significant"] },
  { id: "med20", category: "medical", difficulty: "tough", q: "What is the normal range for the RA (Rheumatoid Factor) blood test?", options: ["Less than 5", "Less than 20", "Less than 50"] },
  { id: "med21", category: "medical", difficulty: "tough", q: "Which test is used to measure gestational diabetes?", options: ["Fasting blood sugar only", "Oral Glucose Tolerance Test (GTT)", "HbA1c only"] },
  { id: "med22", category: "medical", difficulty: "tough", q: "What does a low Glycemic Index (GI) food do to blood sugar?", options: ["Raises it rapidly", "Raises it slowly and steadily", "Has no effect on it"] },
  { id: "med23", category: "medical", difficulty: "tough", q: "Roughly how many nephrons does each kidney contain?", options: ["100,000", "About 1 million", "10 million"] },
  { id: "med24", category: "medical", difficulty: "tough", q: "What does NAFLD stand for?", options: ["New Age Fatty Liver Disorder", "Non-Alcoholic Fatty Liver Disease", "Nerve and Fat Liver Dysfunction"] },
  { id: "med25", category: "medical", difficulty: "tough", q: "What is the fecal calprotectin test used to detect?", options: ["Blood sugar levels", "Inflammation in the intestines", "Kidney function"] },
  { id: "med26", category: "medical", difficulty: "tough", q: "What does a positive Anti-CCP antibody test help diagnose?", options: ["Diabetes", "Rheumatoid Arthritis", "Thyroid disease"] },
  { id: "med27", category: "medical", difficulty: "tough", q: "What is the normal range for fasting blood sugar?", options: ["Below 100 mg/dL", "Below 180 mg/dL", "Below 250 mg/dL"] },
  { id: "med28", category: "medical", difficulty: "tough", q: "What is a normal HbA1c level?", options: ["Below 5.7%", "Above 9%", "Exactly 15%"] },
  { id: "med29", category: "medical", difficulty: "tough", q: "What does elevated CRP (C-Reactive Protein) indicate?", options: ["Inflammation", "Dehydration", "Low sugar"] },
  { id: "med30", category: "medical", difficulty: "tough", q: "What is the function of the pancreas?", options: ["Produces insulin and digestive enzymes", "Filters blood", "Produces bile only"] },
  { id: "med31", category: "medical", difficulty: "tough", q: "What does the TSH test measure?", options: ["Thyroid-stimulating hormone", "Sugar", "Calcium"] },
  { id: "med32", category: "medical", difficulty: "tough", q: "What is insulin resistance?", options: ["Cells respond poorly to insulin", "Cells overreact to insulin", "No insulin exists"] },
  { id: "med33", category: "medical", difficulty: "tough", q: "What does a lipid profile measure?", options: ["Cholesterol and fats", "Blood cells", "Kidney stones"] },
  { id: "med34", category: "medical", difficulty: "tough", q: "What is the difference between LDL and HDL?", options: ["LDL is often 'bad', HDL is 'good'", "LDL is good, HDL is bad", "No difference"] },
  { id: "med35", category: "medical", difficulty: "tough", q: "What does a Vitamin D blood test check?", options: ["Vitamin D levels in blood", "Sugar", "Iron only"] },
  { id: "med36", category: "medical", difficulty: "tough", q: "What does PCOD stand for?", options: ["Polycystic Ovary Disease", "Pancreatic Disorder", "Preventive Care Disorder"] },
  { id: "med37", category: "medical", difficulty: "tough", q: "What is the normal range for triglycerides?", options: ["Below 150 mg/dL", "Above 500 mg/dL", "Exactly 1000 mg/dL"] },
  { id: "med38", category: "medical", difficulty: "tough", q: "What does the term 'gut microbiome' refer to?", options: ["Bacteria living in the gut", "Bacteria on the skin", "Viruses in the air"] },
  { id: "med39", category: "medical", difficulty: "tough", q: "Which test measures kidney function?", options: ["Creatinine", "Cholesterol", "Vitamin D"] },
  { id: "med40", category: "medical", difficulty: "tough", q: "Why does RF emphasize fasting insulin in disease reversal?", options: ["It reveals insulin resistance early", "It is meaningless", "It only measures sugar"] },
  { id: "med41", category: "medical", difficulty: "tough", q: "How many broad types of disease does RF describe?", options: ["3 broad types", "2 broad types (infection-driven and chronic lifestyle-driven)", "4 broad types"] },
  { id: "med42", category: "medical", difficulty: "tough", q: "Roughly how many nerve cells does the gut's Enteric Nervous System contain?", options: ["10 million", "Over 100 million", "1 million"] },
  { id: "med43", category: "medical", difficulty: "tough", q: "What does RF say is the root cause of chronic lifestyle diseases?", options: ["Genetics only", "Bacteria and viruses", "Our lifestyle, food habits, sleep, and emotions"] },

  // ---------------- PROGRAMS (easy) ----------------
  { id: "pro1", category: "programs", difficulty: "easy", q: "What is RF's 'Date with Divine'?", options: ["A 1-day nutrition workshop", "A 2-day retreat teaching meditation and self-transformation", "An online-only course"] },
  { id: "pro2", category: "programs", difficulty: "easy", q: "What does RF say is its main USP compared to other dieticians?", options: ["Weight loss programs", "Disease reversal", "Meal delivery service"] },
  { id: "pro3", category: "programs", difficulty: "easy", q: "How many duration options does RF's Basic program offer?", options: ["1 option only", "Unlimited options", "3 options (2, 4, and 6 months)"] },
  { id: "pro4", category: "programs", difficulty: "easy", q: "In RF's Basic program, how often do you interact with Karan Sir?", options: ["Weekly", "Once, at the start of the program", "Never"] },
  { id: "pro5", category: "programs", difficulty: "easy", q: "Who is the face of RF coaching?", options: ["Karan Sir", "No one", "A faceless group"] },
  { id: "pro6", category: "programs", difficulty: "easy", q: "What is the goal of RF's Basic program?", options: ["Foundational health transformation", "Only weight loss", "Just recipes"] },
  { id: "pro7", category: "programs", difficulty: "easy", q: "Does RF offer one-on-one support?", options: ["Yes, with Karan Sir", "No", "Only through videos"] },
  { id: "pro8", category: "programs", difficulty: "easy", q: "What is the primary focus of RF coaching?", options: ["Whole-person health transformation", "Only dieting", "Only supplements"] },
  { id: "pro9", category: "programs", difficulty: "easy", q: "What does the RF program emphasize about food?", options: ["Real food and lifestyle, not pills", "Supplements as the main fix", "Nothing"] },
  { id: "pro10", category: "programs", difficulty: "easy", q: "What is the entry point into RF coaching?", options: ["A discovery call/intake", "Buying supplements", "Joining a gym"] },
  { id: "pro11", category: "programs", difficulty: "easy", q: "What does RF's disease-reversal approach combine?", options: ["Food, lifestyle, mindset, and medical monitoring", "Surgery", "Only medication"] },
  { id: "pro12", category: "programs", difficulty: "easy", q: "What kind of result does RF promise?", options: ["Health transformation through guidance", "Magic pills", "Instant cures overnight"] },

  // ---------------- PROGRAMS (tough) ----------------
  { id: "pro13", category: "programs", difficulty: "tough", q: "How is RF's approach different from a typical diet plan?", options: ["It addresses root causes instead of temporary restrictions", "They are identical", "RF ignores food"] },
  { id: "pro14", category: "programs", difficulty: "tough", q: "What does RF mean by 'disease reversal'?", options: ["Resolving lifestyle diseases through correction", "Hiding symptoms", "Surgical cure"] },
  { id: "pro15", category: "programs", difficulty: "tough", q: "Which of these does RF's program cover?", options: ["Food, sleep, thoughts, and movement", "Only calories", "Only gym workouts"] },
  { id: "pro16", category: "programs", difficulty: "tough", q: "What is the role of blood tests in RF coaching?", options: ["To track markers and guide reversal", "To sell supplements", "Optional and ignored"] },
  { id: "pro17", category: "programs", difficulty: "tough", q: "What does RF say about the pace of reversal?", options: ["It is a process requiring consistent effort", "Overnight results", "Only genetic luck"] },
  { id: "pro18", category: "programs", difficulty: "tough", q: "What is the significance of the discovery/intake call?", options: ["To assess health and personalize guidance", "To sell a course only", "Just a formality"] },
  { id: "pro19", category: "programs", difficulty: "tough", q: "What does RF recommend tracking during the program?", options: ["Food, sleep, and energy levels", "Nothing", "Only weight"] },
  { id: "pro20", category: "programs", difficulty: "tough", q: "What is the role of accountability in RF?", options: ["Regular check-ins keep you on track", "No accountability", "Only monthly billing"] },
  { id: "pro21", category: "programs", difficulty: "tough", q: "What does RF say about the maintenance phase after reversal?", options: ["Healthy habits must continue", "You can return to old habits", "Only diet pills"] },
  { id: "pro22", category: "programs", difficulty: "tough", q: "What is RF's stance on medication during reversal?", options: ["Work with your doctor and taper under guidance", "Stop abruptly", "Ignore doctors"] },
  { id: "pro23", category: "programs", difficulty: "tough", q: "What is the 'why' in RF coaching?", options: ["Connecting goals to purpose for motivation", "A marketing term", "A password"] },
  { id: "pro24", category: "programs", difficulty: "tough", q: "How does RF personalize programs?", options: ["Based on individual health reports", "Same plan for everyone", "Random selection"] },
  { id: "pro25", category: "programs", difficulty: "tough", q: "What does RF say about family support in transformation?", options: ["It helps sustain change", "It is irrelevant", "It is harmful"] },
  { id: "pro26", category: "programs", difficulty: "tough", q: "What does the weekly interaction with Karan Sir include?", options: ["Guidance, doubt-clearing, and progress review", "Just a greeting", "A quiz only"] },
  { id: "pro27", category: "programs", difficulty: "tough", q: "What does RF emphasize about supplements?", options: ["Used only when genuinely needed", "As the primary treatment", "Never needed"] },
  { id: "pro28", category: "programs", difficulty: "tough", q: "What is the typical first phase of an RF transformation?", options: ["Cleaning up food and habits", "Buying expensive equipment", "Nothing"] },
  { id: "pro29", category: "programs", difficulty: "tough", q: "What does RF say about the gut in disease reversal?", options: ["Healing the gut is foundational", "It doesn't matter", "Only external creams"] },
  { id: "pro30", category: "programs", difficulty: "tough", q: "What is RF's view on quick-fix products?", options: ["Avoid them, focus on habits", "Use them daily", "They replace food"] },
  { id: "pro31", category: "programs", difficulty: "tough", q: "How does the RF program handle sleep issues?", options: ["Addresses them as part of health", "Ignores them", "Prescribes only pills"] },
  { id: "pro32", category: "programs", difficulty: "tough", q: "What does 'transformation' mean in RF?", options: ["Lasting change in habits and health", "Temporary weight drop", "A one-time event"] },
  { id: "pro33", category: "programs", difficulty: "tough", q: "How does RF define success?", options: ["Improved health markers and habits", "Only the number on the scale", "Meeting all doctors"] },
  { id: "pro34", category: "programs", difficulty: "tough", q: "What is the role of education in RF?", options: ["Teaching you to manage your own health", "Keeping you dependent", "Not important"] },
  { id: "pro35", category: "programs", difficulty: "tough", q: "What does RF say about relapses?", options: ["They are part of the journey, get back on track", "You should give up", "They never happen"] },
  { id: "pro36", category: "programs", difficulty: "tough", q: "What is RF's approach to weight management?", options: ["Fix the root cause first", "More restriction always", "Skip all food"] },
  { id: "pro37", category: "programs", difficulty: "tough", q: "What does RF say about coaching vs just content?", options: ["Guidance and accountability make the difference", "They are the same", "Videos alone are enough"] },
];

module.exports = { questions };
