// Client-safe: questions and options only, no correct-answer indices here.
// Correct answers live in lib/answerKey.js (server-only).
const questions = [
  { q: "How many things does RF recommend avoiding on a daily basis?", options: ["5", "3", "7"] },
  { q: "Which of these is the exception RF says is fine occasionally (not on the daily-avoid list)?", options: ["Deep fried food", "Packet food", "Fresh fruit"] },
  { q: "According to RF, when do mammals naturally produce milk?", options: ["Only when pregnant or lactating", "All the time", "Only during childhood"] },
  { q: "What health issues does RF link to hormonal imbalance from regular milk product consumption?", options: ["Only weight gain", "Only thyroid issues", "Overweight, thyroid problems, and PCOD"] },
  { q: "Into how many parts does RF divide all food?", options: ["2", "5", "3"] },
  { q: "Which of RF's three food categories should be eaten the least?", options: ["Plant food", "Fruits", "Animal food"] },
  { q: "Where is fiber found, according to RF?", options: ["In animal food", "Only in plant food", "In packet food"] },
  { q: "What percentage of our immunity lies in the gut, according to RF?", options: ["50%", "70%", "85%"] },
  { q: "What is the food source for the trillions of gut bacteria, per RF?", options: ["Protein", "Sugar", "Fiber"] },
  { q: "How many main concepts does RF follow?", options: ["5", "6", "8"] },
  { q: "What is RF's core philosophy instead of eating less?", options: ["Eating right", "Eating less", "Skipping meals"] },
  { q: "How many times a day does RF recommend eating cooked food (except for weight-gain cases)?", options: ["3 times", "2 times", "4 times"] },
  { q: "How many hours of intermittent fasting does RF recommend for everyone?", options: ["8 hours", "12 hours", "16 hours"] },
  { q: "How many pillars of good health does RF identify?", options: ["3", "5", "7"] },
  { q: "What are the two things RF says go into our body/mind every day?", options: ["Sleep and exercise", "Food and our thoughts/emotions", "Medicine and rest"] },
  { q: "How many broad types of disease does RF describe?", options: ["3 broad types", "2 broad types (infection-driven and chronic lifestyle-driven)", "4 broad types"] },
  { q: "What does RF say is the root cause of chronic lifestyle diseases?", options: ["Genetics only", "Bacteria and viruses", "Our lifestyle, food habits, sleep, and emotions"] },
  { q: "What does RF say we should focus on, rather than counting calories?", options: ["Nutrients", "Portion size", "Calorie counting"] },
  { q: "What is a 'phytonutrient', according to RF?", options: ["A synthetic vitamin supplement", "A type of protein supplement", "Plant-based compounds/colors that provide antioxidant benefits"] },
  { q: "Roughly how many thoughts does a person have per day, according to RF?", options: ["10,000-20,000", "60,000-70,000", "100,000+"] },
  { q: "When does most of the immune system's cancer-cell killing happen, according to RF?", options: ["During the day", "In the first half of the night", "In the second half of the night"] },
  { q: "How many rules does RF give for drinking water?", options: ["5 rules", "3 rules", "7 rules"] },
  { q: "What does RF say is the world's #1 source of calcium (not milk)?", options: ["Almonds", "White sesame seeds", "Spinach"] },
  { q: "Why does RF say caffeine shouldn't be had daily?", options: ["It has too many calories", "It's a stimulant and not gut-friendly", "It causes weight gain directly"] },
  { q: "Which energy centers does RF's breathwork aim to release lower emotions from?", options: ["The upper 3 energy centers", "The lower 3 energy centers", "All 8 energy centers equally"] },
  { q: "According to RF, epigenetics shows our gene expression is influenced by what?", options: ["Only inherited DNA, unchangeable", "Our lifestyle, food, sleep, and emotions", "Random chance"] },
  { q: "How many main things does RF's unique meditation program teach?", options: ["3 things", "5 things", "4 things"] },
  { q: "How many duration options does RF's Basic program offer?", options: ["1 option only", "Unlimited options", "3 options (2, 4, and 6 months)"] },
  { q: "In RF's Basic program, how often do you interact with Karan Sir?", options: ["Weekly", "Once, at the start of the program", "Never"] },
  { q: "What is RF's 'Date with Divine'?", options: ["A 1-day nutrition workshop", "A 2-day retreat teaching meditation and self-transformation", "An online-only course"] },
  { q: "What does RF say is its main USP compared to other dieticians?", options: ["Weight loss programs", "Disease reversal", "Meal delivery service"] },
  { q: "According to RF, what should be done if someone is deficient in D3 or B12 on a plant-based diet?", options: ["Nothing, plant food covers it entirely", "Take a supplement for the deficient one", "Add more milk products"] },
  { q: "Roughly how many nerve cells does the gut's Enteric Nervous System contain?", options: ["10 million", "Over 100 million", "1 million"] },
  { q: "What percentage of serotonin (the mood hormone) is produced in the gut, per RF?", options: ["50%", "Around 90%", "10%"] },
  { q: "What hormone does RF call the 'hunger hormone'?", options: ["Leptin", "Ghrelin", "Insulin"] },
  { q: "What hormone tells your brain you're full, per RF's list?", options: ["Ghrelin", "Leptin", "Cortisol"] },
  { q: "What does the C-peptide blood test measure?", options: ["Blood sugar directly", "How much insulin the pancreas is producing", "Cholesterol levels"] },
  { q: "What does the vagus nerve connect the brain to?", options: ["Only the lungs", "Organs like the heart, lungs, and gut", "The skin"] },
  { q: "What is considered the normal range for fasting insulin?", options: ["Less than 5 µIU/mL", "Less than 25 µIU/mL", "Less than 100 µIU/mL"] },
  { q: "What does high fasting insulin usually indicate?", options: ["Excellent metabolic health", "Pre-diabetes and insulin resistance", "Nothing significant"] },
  { q: "What is the normal range for the RA (Rheumatoid Factor) blood test?", options: ["Less than 5", "Less than 20", "Less than 50"] },
  { q: "What does HDL stand for?", options: ["Heavy Density Lipid", "High-Density Lipoprotein", "Hormonal Density Level"] },
  { q: "Which test is used to measure gestational diabetes?", options: ["Fasting blood sugar only", "Oral Glucose Tolerance Test (GTT)", "HbA1c only"] },
  { q: "What does a low Glycemic Index (GI) food do to blood sugar?", options: ["Raises it rapidly", "Raises it slowly and steadily", "Has no effect on it"] },
  { q: "What is often called the 'powerhouse of the cell'?", options: ["Mitochondria", "Nucleus", "Ribosome"] },
  { q: "What happens to ghrelin levels when we don't get enough sleep?", options: ["It increases, causing more hunger", "It decreases", "It stays exactly the same"] },
  { q: "Roughly how many nephrons does each kidney contain?", options: ["100,000", "About 1 million", "10 million"] },
  { q: "What does NAFLD stand for?", options: ["New Age Fatty Liver Disorder", "Non-Alcoholic Fatty Liver Disease", "Nerve and Fat Liver Dysfunction"] },
  { q: "What is the fecal calprotectin test used to detect?", options: ["Blood sugar levels", "Inflammation in the intestines", "Kidney function"] },
  { q: "What does a positive Anti-CCP antibody test help diagnose?", options: ["Diabetes", "Rheumatoid Arthritis", "Thyroid disease"] },
];

module.exports = { questions };
